[[edge_functions]]
  function = "og"
  path = "/og"

[[edge_functions]]
  function = "theme-toggle"
  path = "/theme-toggle"

[[edge_functions]]
  function = "theme-toggle"
  path = "/*/theme-toggle"

[[edge_functions]]
  function = "theme-toggle"
  path = "/"

[[edge_functions]]
  function = "theme-toggle"
  path = "/posts/*"

[[edge_functions]]
  function = "theme-toggle"
  path = "/about"

[[edge_functions]]
  function = "theme-toggle"
  path = "/content"

[[edge_functions]]
  function = "theme-toggle"
  path = "/*/"

[[edge_functions]]
  function = "theme-toggle"
  path = "/guestbook/*"

[[edge_functions]]
  function = "theme-toggle"
  path = "/post/*"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"