[[edge_functions]]
  function = "og"
  path = "/og"

[[edge_functions]]
  function = "theme-toggle"
  path = "/theme-toggle"

[[edge_functions]]
  function = "theme-toggle"
  path = "/*/theme-toggle"

[[edge_functions]]
  function = "theme-toggle"
  path = "/*"